name: Apply AKS

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'

jobs:
  plan-dev:
    name: 'Terraform APPLY [Criando AKS]'
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.set_aks.outputs.aks_cluster_name }}
      output2: ${{ steps.set_aks.outputs.resource_group_name }}
    env:
      TF_WORKING_DIR: 'terraform'

    defaults:
      run:
        shell: bash
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run Azure CLI command
        run: |
          az account show

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform fmt
        id: fmt
        run: terraform fmt

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Debug Terraform Outputs
        run: terraform output

      - name: Coletando informações do AKS
        id: set_aks
        run: |
          CLUSTER_NAME=$(terraform output -raw aks_cluster_name)
          echo "::set-output name=aks_cluster_name::$CLUSTER_NAME"

          GROUP_NAME=$(terraform output -raw resource_group_name )
          echo "::set-output name=resource_group_name::$GROUP_NAME"

  kubectl-setup:
    name: 'Instalação do kubectl'
    needs: 
      - plan-dev
    runs-on: ubuntu-latest
    steps:
      - name: Obtém credencias do cluster AKS criado
        run: |
          az aks get-credentials -g ${{ needs.plan-dev.outputs.output2 }} -n ${{ needs.plan-dev.outputs.output1 }}

      - name: Install Kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          mv ./kubectl /usr/local/bin

      - name: List All PODS
        run: |
          kubectl get po -ALL
