name: Plan EC2

on:
  pull_request:
    paths:
      - 'terraform/**'

jobs:
  plan-dev:
    name: 'Terraform APPLY [Criando vm EC2]'
    runs-on: ubuntu-latest
    env:
      TF_WORKING_DIR: 'terraform'

    defaults:
      run:
        shell: bash
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run Azure CLI command
        run: |
          az account show

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform fmt
        id: fmt
        run: terraform fmt

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Debug Terraform Outputs
        run: terraform output

      # - name: Coletando informações do AKS
      #   id: set_aks
      #   run: |
      #     PUBLIC_IP=$(terraform output -raw public_ip | grep -E -o "([0-9]{1,3}[\.]){3}[0-9]{1,3}")
      #     echo "::set-output name=IP::$PUBLIC_IP"

      #     INSTANCE_ID=$(terraform output -raw instance_id | grep -oE 'i-[a-zA-Z0-9]+')
      #     echo "::set-output name=instance_id::$INSTANCE_ID"

