name: Destroy aks

on:
  workflow_dispatch:
    inputs:
      dir:
        description: 'Destroy Resource'
        required: true
        default: 'aks'

jobs:
  destroy-ec2:
    name: 'Terraform DESTROY'
    runs-on: ubuntu-latest
    env:
      TF_WORKING_DIR: ${{ github.event.inputs.dir }}

    defaults:
      run: 
        shell: bash
        working-directory: ${{ env.TF_WORKING_DIR }} 

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run Azure CLI command
        run: |
          az account show

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform fmt
        id: fmt
        run: terraform fmt 

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Destroy
        run: terraform destroy -auto-approve

      